spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'TRUE'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${db_password}
    username: ${db_username}
    url: jdbc:mysql://localhost:3306/hotel_management?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  servlet:
    multipart:
    max-file-size: 5MB
    max-request-size: 5MB
    file-size-threshold: 2KB
    security:
      jwt:
        secret-key: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D
        expire-length: 3600000
logging:
  level:
    org:
      hibernate:
        type:
          descriptor: TRACE
        SQL: DEBUG
      nodeValue: WARN
    blog: WARN

server:
  port: 8080
