/*
07.	New students
Some students are not signed up for any course but want to be registered in the system with accounts.
To find the account details write a query that returns:
full_name, username and password for all students
who do not have any assigned course.
The full_name is their first_name and last_name separated by whitespace.
The username is generated by using 10 characters from their email starting from the 2nd letter.
The password is their phone number but reversed.
Order by password in descending order.
Required Columns
•	full_name (first_name + " " + last_name)
•	username (10 characters long starting from the 2nd)
•	password (phone number but reversed)
*/

USE universities_db;

SELECT CONCAT_WS(' ',s.first_name, s.last_name) AS full_name, SUBSTRING(s.email, 2, 10) AS username, REVERSE(s.phone) AS password
FROM students s
LEFT JOIN students_courses sc ON s.id = sc.student_id
LEFT JOIN courses c ON sc.course_id = c.id
WHERE course_id IS NULL
ORDER BY password DESC;
